project_id = "dfkoxuokfkttjhfjcecx"

[functions.send-usage-alert]
verify_jwt = false

[functions.ayn-webhook]
verify_jwt = true

[functions.file-upload]
verify_jwt = true


[functions.ai-email-assistant]
verify_jwt = true

[functions.generate-suggestions]
verify_jwt = true

[functions.generate-eye-behaviors]
verify_jwt = true

[functions.send-application-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-reply-email]
verify_jwt = true

[functions.support-bot]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = false

[functions.send-ticket-reply]
verify_jwt = true

[functions.verify-admin-pin]
verify_jwt = true

[functions.generate-emotion-keywords]
verify_jwt = false

[functions.analyze-emotion]
verify_jwt = true
