project_id = "dfkoxuokfkttjhfjcecx"

[functions.ayn-webhook]
verify_jwt = true

[functions.file-upload]
verify_jwt = true

[functions.custom-auth-emails]
verify_jwt = false

[functions.ai-email-assistant]
verify_jwt = true

[functions.generate-suggestions]
verify_jwt = true

[functions.generate-eye-behaviors]
verify_jwt = true

[functions.send-application-email]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-reply-email]
verify_jwt = true

[functions.support-bot]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = false

[functions.send-ticket-reply]
verify_jwt = true
